INSERT INTO directors (firstname, lastname, birth_year, sex, country_of_birth)
VALUES ('Steven', 'Spielberg', 1946, 'male', 'US'),
        ('Quentin', 'Tarantino', 1963, 'male', 'US'),
        ('Martin', 'Scorsese', 1942, 'male', 'US'),
        ('Christopher', 'Nolan', 1970, 'male', 'Great Britain'),
        ('James', 'Cameron', 1954, 'male', 'Canada');

INSERT INTO films (title, release_year, budget, duration, director_id)
VALUES ('Ready player one', 2018, 175000000, 140,
        (SELECT d.id FROM directors d WHERE firstname = 'Steven' AND lastname = 'Spielberg')),
       ('Catch me if you can', 2002, 52000000, 141,
        (SELECT d.id FROM directors d WHERE firstname = 'Steven' AND lastname = 'Spielberg')),
       ('Schindlers list', 1993, 22000000, 195,
        (SELECT d.id FROM directors d WHERE firstname = 'Steven' AND lastname = 'Spielberg')),
       ('Inglourious Basterds', 2009, 70000000, 153,
        (SELECT d.id FROM directors d WHERE firstname = 'Quentin' AND lastname = 'Tarantino')),
       ('Pulp fiction', 1994, 8000000, 154,
        (SELECT d.id FROM directors d WHERE firstname = 'Quentin' AND lastname = 'Tarantino')),
       ('Once upon a time in Hollywood', 2019, 90000000, 161,
        (SELECT d.id FROM directors d WHERE firstname = 'Quentin' AND lastname = 'Tarantino')),
       ('The wolf of Wall Street', 2013, 100000000, 180,
        (SELECT d.id FROM directors d WHERE firstname = 'Martin' AND lastname = 'Scorsese')),
       ('Shutter island', 2013, 80000000, 138,
        (SELECT d.id FROM directors d WHERE firstname = 'Martin' AND lastname = 'Scorsese')),
       ('Interstellar', 2014, 165000000, 169,
        (SELECT d.id FROM directors d WHERE firstname = 'Christopher' AND lastname = 'Nolan')),
       ('Inception', 2010, 160000000, 148,
        (SELECT d.id FROM directors d WHERE firstname = 'Christopher' AND lastname = 'Nolan')),
       ('Avatar', 2009, 237000000, 162,
        (SELECT d.id FROM directors d WHERE firstname = 'James' AND lastname = 'Cameron')),
       ('Titanic', 1997, 200000000, 194,
        (SELECT d.id FROM directors d WHERE firstname = 'James' AND lastname = 'Cameron')),
       ('The Terminator', 1984, 6400000, 108,
        (SELECT d.id FROM directors d WHERE firstname = 'James' AND lastname = 'Cameron'));